name: Android CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Decrypt signing key
      run: openssl aes-256-cbc -d -pass pass:'$SECRET_PASSWORD' -salt -pbkdf2 -in secret.enc -out releasekey.jks
    - name: Make Gradle runnable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew build
