name: Release Workflow

on:
  push:
    tags:
      - 'v*'
    paths-ignore:
      - '_docs/**'
      - 'docs/**'
      - 'README.md'
      - 'LICENSE'

jobs:
  build:
    name: Build Apk
    runs-on: ubuntu-latest
    env:
      SECRET_PASSWORD: ${{ secrets.SECRET_PASSWORD }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
      KEYSTORE_ALIAS_PASSWORD: ${{ secrets.KEYSTORE_ALIAS_PASSWORD }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8

      - name: Decrypt Secrets
        run: openssl aes-256-cbc -d -pass env:SECRET_PASSWORD -salt -pbkdf2 -in app/secrets.enc -out app/secrets.tar.gz

      - name: Uncompress Secrets
        run: tar xzf app/secrets.tar.gz -C app/

      - name: Make Gradle Runnable
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: Upload Artifact
        uses: actions/upload-artifact@v1
        if: success() && (!contains(github.ref, 'development'))
        with:
          name: apk
          path: app/build/outputs/apk/release/app-release.apk

  release:
    name: Create Release
    needs: build
    if: (!contains(github.ref, 'development'))
    runs-on: ubuntu-latest
    steps:
      - name: Download Artifact
        uses: actions/download-artifact@v1
        with:
          name: apk
          path: ./

      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: HALauncher ${{ github.ref }}
          body: ''
          draft: false
          prerelease: ${{ contains(github.ref, '-beta') || contains(github.ref, '-rc') }}

      - name: Upload Apk
        uses: actions/upload-release-asset@v1.0.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./app-release.apk
          asset_name: HALauncher.apk
          asset_content_type: application/vnd.android.package-archive
