
name: Android CI

on:
  push:
    paths:
      - '!docs/**'
    branches: 
      - master

jobs:  
  build:
    runs-on: ubuntu-latest
    env:
      SECRET_PASSWORD: ${{ secrets.SECRET_PASSWORD }}
      KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      KEYSTORE_ALIAS: ${{ secrets.KEYSTORE_ALIAS }}
      KEYSTORE_ALIAS_PASSWORD: ${{ secrets.KEYSTORE_ALIAS_PASSWORD }}
    steps:
    - uses: actions/checkout@v1
    - name: set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Decrypt signing key
       
      run: openssl aes-256-cbc -d -pass env:SECRET_PASSWORD -salt -pbkdf2 -in app/secret.enc -out app/releasekey.jks
    - name: Make Gradle runnable
      run: chmod +x ./gradlew
    - name: Build with Gradle
      run: ./gradlew assembleRelease
