name: Test Build

on:
  push:
    branches:
      - development
    paths-ignore:
      - _docs/**
      - docs/**
      - README.md
      - LICENSE

jobs:
  test:
    name: Test
    runs-on: ubuntu-latest
    env:
      SECRET_PASSWORD: ${{ secrets.SECRET_PASSWORD }}

    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Set up JDK 1.8
        uses: actions/setup-java@v1
        with:
          java-version: 1.8
      
      - name: Decrypt Secrets
        run: openssl aes-256-cbc -d -pass env:SECRET_PASSWORD -salt -pbkdf2 -in app/secrets.enc -out app/secrets.tar.gz

      - name: Uncompress Secrets
        run: tar xzf app/secrets.tar.gz -C app/
      
      - name: Make Gradle Runnable
        run: chmod +x ./gradlew

      - name: Run Android Linter
        run: ./gradlew lintDebug

      - name: Run Kotlin Linter
        run: ./gradlew ktlintDebugCheck

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest --stacktrace

      - name: Upload Unit Test Logs
        uses: actions/upload-artifact@v1
        with:
          name: unit-tests-logs
          path: app/build/reports/tests/testDebugUnitTest/index.html

      - name: Assemble Debug APK
        run: ./gradlew assembleDebug
